### ISSUE TITLE
Support pubsub

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-SDK-Android#13]
### Tasks
- [x] Bridging with the [WebSocket Library](https://github.com/TooTallNate/Java-WebSocket/)
- [x] Subscribe / Unsubscribe
- [x] Publish
- [x] Reconnection after connection close
- [x] Queue up events (subs, unsubs and pubs) when not yet connected
- [x] Test Cases
- [x] Sample Project
- [x] Documentation
