### ISSUE TITLE
Support assets

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-SDK-Android#43]
### Tasks

- [x] Add asset model
- [x] Add asset serialization in record serialization
- [x] Implement asset upload mechanism
- [x] Update sample project
- [x] Add test cases
