### ISSUE TITLE
Support Geo Data in Record

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-SDK-Android#56]
### Tasks
- [x] Support Location Field in Records
- [x] Support distance related query predicate
- [x] Support distance related sorting
- [x] Support transient includes distance
- [x] Update Sample Project
- [x] Documentation
